name: Deploy basic-node via Argo CD

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit message'
        required: true
        default: 'Deploy basic-node via Argo CD'
  push:
    branches:
      - main
    paths:
      - 'gitops/argocd/basic-nodejs/**'

jobs:
  publish-image:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./gitops/argocd/basic-nodejs
          file: ./gitops/argocd/basic-nodejs/Dockerfile
          push: true
          tags: cheulong/basic-nodejs:${{ github.sha }}
  
  update-manifests:
    name: Update Kubernetes Manifests
    runs-on: ubuntu-latest
    needs: publish-image
    env:
      GIT_PAT: ${{ secrets.GIT_PAT }}
      GIT_USERNAME: ${{ vars.GIT_USERNAME }}
    steps:
      - name: Update image tag in values.yaml
        run: |
          git clone https://github.com/${{ vars.GIT_USERNAME }}/devops.git
          
          sed -i "s/tag: .*/tag: \"${{ github.sha }}\"/" devops/gitops/argocd/basic-nodejs-deployment/api1/values.yaml
          
          git config user.name "github-action"
          git config user.email "devops@searcheulong.com"
          git commit -am "Update image to ${{ github.sha }}"
          git push origin main
